# Generated by Django 3.2.8 on 2021-10-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField()),
                ('genre', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('Song_id', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('like', models.IntegerField(blank=True, default=None, null=True)),
                ('dislike', models.IntegerField(blank=True, null=True)),
                ('songcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone.song')),
            ],
        ),
    ]
